<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_AutoClean_Filter_Bollfilter" Id="{8227a48a-9674-4888-9564-c0746903889e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_AutoClean_Filter_Bollfilter EXTENDS FB_BaseDevice IMPLEMENTS I_Device
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_AutoClean_Filter_Bollfilter">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>