<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_HVAC_RND_ModbusApadtor" Id="{04beb52c-ae32-40c4-bc43-713399989349}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HVAC_RND_ModbusApadtor EXTENDS FB_BaseDevice

VAR
	
	// ----------------- Modbus Variables -----------//
	// Written in accordance with the modbus manuial supplied by vendor
	// https://drive.google.com/file/d/1Gl1Z8UXsnYqQFCh63b19Rq_Jpmyq9qef/view?usp=sharing
	
	// -------------------READ ONLY ---------------//
	bReady: BOOL;
	
	// -------------------READ / WRITE ---------------//
	bManagedDIINetAdr: BOOL;
	bDIINetMasterFlag: BOOL;
	bDIINet_Comms_StartStopFlag: BOOL;
	
	
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_HVAC_RND_ModbusApadtor">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>