<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_AutoGreaser" Id="{51e4fc2c-b6de-4b44-a745-7ffb6a961ee5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_AutoGreaser EXTENDS FB_BaseDevice
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_AutoGreaser">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>